### ISSUE TITLE
Data processing step needed

### ISSUE THREAD

**Issue by lilianabounegru** [PublicDataLab/zeehaven#1]
For zeehaven to play a role equivalent to 4CAT when it comes to accessing zeeschuimer data in csv format, there is a step that is implemented in 4CAT and that would need to be implemented in zeehaven too to map the ndjson categories into readable and useful categories for the csv user.

Here are the scripts that 4CAT uses to convert zeeschuimer ndjson files into csvs:
instagram: https://github.com/digitalmethodsinitiative/4cat/blob/master/datasources/instagram/search_instagram.py 
tiktok: https://github.com/digitalmethodsinitiative/4cat/blob/master/datasources/tiktok/search_tiktok.py

The 4CAT scripts for processing the other zeehaven data sources can be found here: https://github.com/digitalmethodsinitiative/4cat/tree/master/datasources

Would it be possible to implement these in zeehaven too?

**Comment by jwyg** [comment]
@iaine added processing for instagram + twitter bce65df7bae151e3a5b48f90f06c757b056a9b8e - thanks iain! <3
